# backend/app/utils/pdf_generator.py
"""
PDF Generator
=============
Utilities for generating PDF documents from text.

Uses ReportLab for PDF generation with Indian legal formatting.
"""

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_LEFT
from reportlab.pdfgen import canvas
from datetime import datetime
from pathlib import Path
from typing import Optional
import os


class IndianLegalPDFGenerator:
    """
    Generator for Indian legal documents in PDF format.
    
    Features:
    - A4 page size
    - Professional formatting
    - Page numbers
    - Header/footer with disclaimer
    """
    
    def __init__(self):
        """Initialize PDF generator."""
        self.page_size = A4
        self.margin = 1 * inch
        
    def generate_pdf(
        self,
        content: str,
        output_path: str,
        title: str,
        metadata: Optional[dict] = None
    ) -> str:
        """
        Generate a PDF from text content.
        
        Args:
            content: Text content of the document
            output_path: Path to save the PDF
            title: Document title
            metadata: Optional metadata (author, subject, etc.)
            
        Returns:
            Path to generated PDF file
        """
        # Ensure output directory exists
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        
        # Create PDF document
        doc = SimpleDocTemplate(
            output_path,
            pagesize=self.page_size,
            rightMargin=self.margin,
            leftMargin=self.margin,
            topMargin=self.margin,
            bottomMargin=self.margin,
            title=title,
            author=metadata.get("author", "AI Legal Assistant") if metadata else "AI Legal Assistant",
        )
        
        # Build content
        story = []
        styles = self._create_styles()
        
        # Add title
        story.append(Paragraph(title, styles['DocTitle']))
        story.append(Spacer(1, 0.3 * inch))
        
        # Add metadata if provided
        if metadata:
            if metadata.get("date"):
                story.append(Paragraph(
                    f"<b>Date:</b> {metadata['date']}",
                    styles['Normal']
                ))
                story.append(Spacer(1, 0.1 * inch))
        
        # Add main content
        # Split by paragraphs
        paragraphs = content.split('\n\n')
        
        for para_text in paragraphs:
            para_text = para_text.strip()
            if not para_text:
                continue
            
            # Check if it's a heading (all caps or starts with specific patterns)
            if self._is_heading(para_text):
                story.append(Spacer(1, 0.2 * inch))
                story.append(Paragraph(para_text, styles['DocHeading']))
                story.append(Spacer(1, 0.1 * inch))
            else:
                # Regular paragraph
                story.append(Paragraph(para_text, styles['BodyText']))
                story.append(Spacer(1, 0.15 * inch))
        
        # Add disclaimer
        story.append(Spacer(1, 0.5 * inch))
        story.append(Paragraph("_" * 80, styles['Normal']))
        story.append(Spacer(1, 0.2 * inch))
        
        disclaimer = """
        <b>DISCLAIMER:</b> This document was generated by an AI Legal Assistant and is provided 
        for informational purposes only. This is NOT legal advice. This document should be 
        reviewed by a qualified advocate registered with the Bar Council of India before use. 
        The creators and operators of this AI system accept no liability for any actions taken 
        based on this document.
        """
        story.append(Paragraph(disclaimer, styles['DocDisclaimer']))
        
        # Add generation info
        story.append(Spacer(1, 0.2 * inch))
        generation_info = f"Generated on: {datetime.now().strftime('%d %B %Y at %I:%M %p')}"
        story.append(Paragraph(generation_info, styles['DocFooter']))
        
        # Build PDF
        doc.build(story, onFirstPage=self._add_page_number, onLaterPages=self._add_page_number)
        
        return output_path
    
    def _create_styles(self):
        """Create custom paragraph styles."""
        styles = getSampleStyleSheet()
        
        # Custom title style (avoid conflict with built-in 'Title')
        if 'DocTitle' not in styles:
            styles.add(ParagraphStyle(
                name='DocTitle',
                parent=styles['Title'],
                fontSize=18,
                textColor='#000000',
                spaceAfter=12,
                alignment=TA_CENTER,
                fontName='Helvetica-Bold',
            ))
        
        # Custom heading style (avoid conflict with built-in 'Heading2')
        if 'DocHeading' not in styles:
            styles.add(ParagraphStyle(
                name='DocHeading',
                parent=styles['Heading2'],
                fontSize=14,
                textColor='#000000',
                spaceAfter=6,
                fontName='Helvetica-Bold',
            ))
        
        # Body text style is already in default styles, so we can use it directly
        # But let's make sure BodyText exists
        if 'BodyText' not in styles:
            styles.add(ParagraphStyle(
                name='BodyText',
                parent=styles['Normal'],
                fontSize=11,
                leading=16,
                alignment=TA_JUSTIFY,
                fontName='Times-Roman',
            ))
        
        # Custom disclaimer style
        if 'DocDisclaimer' not in styles:
            styles.add(ParagraphStyle(
                name='DocDisclaimer',
                parent=styles['Normal'],
                fontSize=9,
                textColor='#666666',
                alignment=TA_JUSTIFY,
                fontName='Helvetica',
                borderWidth=1,
                borderColor='#CCCCCC',
                borderPadding=10,
                backColor='#F5F5F5',
            ))
        
        # Custom footer style
        if 'DocFooter' not in styles:
            styles.add(ParagraphStyle(
                name='DocFooter',
                parent=styles['Normal'],
                fontSize=8,
                textColor='#999999',
                alignment=TA_CENTER,
                fontName='Helvetica',
            ))
        
        return styles
    
    def _is_heading(self, text: str) -> bool:
        """Determine if text should be formatted as a heading."""
        # All caps and short
        if text.isupper() and len(text) < 100:
            return True
        
        # Starts with common heading patterns
        heading_patterns = [
            'ARTICLE', 'SECTION', 'CLAUSE', 'SCHEDULE',
            'WITNESSETH', 'WHEREAS', 'NOW THEREFORE',
            'DEFINITIONS', 'PREAMBLE', 'RECITALS'
        ]
        
        for pattern in heading_patterns:
            if text.strip().upper().startswith(pattern):
                return True
        
        return False
    
    def _add_page_number(self, canvas, doc):
        """Add page number to each page."""
        canvas.saveState()
        
        # Add page number at bottom
        page_num = canvas.getPageNumber()
        text = f"Page {page_num}"
        canvas.setFont('Helvetica', 9)
        canvas.drawCentredString(
            self.page_size[0] / 2,
            0.5 * inch,
            text
        )
        
        canvas.restoreState()


# ============================================
# HELPER FUNCTIONS
# ============================================
def generate_legal_pdf(
    content: str,
    output_path: str,
    title: str,
    metadata: Optional[dict] = None
) -> str:
    """
    Helper function to generate a legal PDF.
    
    Args:
        content: Document text content
        output_path: Path to save PDF
        title: Document title
        metadata: Optional metadata
        
    Returns:
        Path to generated PDF
    """
    generator = IndianLegalPDFGenerator()
    return generator.generate_pdf(content, output_path, title, metadata)