"""Initial migration - create all tables

Revision ID: 2181ed1439fc
Revises: 
Create Date: 2025-12-07 18:37:13.770009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2181ed1439fc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment="Template name (e.g., 'Non-Disclosure Agreement')"),
    sa.Column('slug', sa.String(length=100), nullable=False, comment="URL-friendly identifier (e.g., 'nda')"),
    sa.Column('description', sa.Text(), nullable=True, comment='Description of when to use this template'),
    sa.Column('category', sa.String(length=100), nullable=False, comment='Category: contracts, agreements, notices, letters'),
    sa.Column('template_body', sa.Text(), nullable=False, comment='Template text with {{placeholders}}'),
    sa.Column('form_schema', sa.JSON(), nullable=False, comment='JSON schema defining form fields'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether template is available for use'),
    sa.Column('is_premium', sa.Boolean(), nullable=False, comment='Premium template (future feature)'),
    sa.Column('usage_count', sa.Integer(), nullable=False, comment='Number of times this template was used'),
    sa.Column('applicable_laws', sa.JSON(), nullable=True, comment="Relevant Indian laws (e.g., ['Indian Contract Act, 1872'])"),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_templates'))
    )
    op.create_index(op.f('ix_templates_category'), 'templates', ['category'], unique=False)
    op.create_index(op.f('ix_templates_id'), 'templates', ['id'], unique=False)
    op.create_index(op.f('ix_templates_name'), 'templates', ['name'], unique=True)
    op.create_index(op.f('ix_templates_slug'), 'templates', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False, comment='Unique user identifier'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='User email address (used for login)'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='Bcrypt hashed password'),
    sa.Column('full_name', sa.String(length=255), nullable=False, comment="User's full display name"),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether the account is active'),
    sa.Column('is_admin', sa.Boolean(), nullable=False, comment='Whether user has admin privileges'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Account creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Last update timestamp'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='ID of user who uploaded this document'),
    sa.Column('filename', sa.String(length=255), nullable=False, comment='Stored filename (UUID-based)'),
    sa.Column('original_name', sa.String(length=255), nullable=False, comment='Original filename uploaded by user'),
    sa.Column('file_type', sa.String(length=50), nullable=False, comment='File extension: pdf, docx, txt'),
    sa.Column('file_size', sa.Integer(), nullable=False, comment='File size in bytes'),
    sa.Column('file_path', sa.String(length=500), nullable=False, comment='Path to stored file'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Processing status: pending, processing, ready, failed'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if processing failed'),
    sa.Column('chunk_count', sa.Integer(), nullable=False, comment='Number of text chunks extracted'),
    sa.Column('page_count', sa.Integer(), nullable=True, comment='Number of pages (for PDFs)'),
    sa.Column('word_count', sa.Integer(), nullable=True, comment='Approximate word count'),
    sa.Column('summary', sa.Text(), nullable=True, comment='AI-generated document summary'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True, comment='When processing completed'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_documents_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.create_table('generated_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False, comment='User-provided document title'),
    sa.Column('form_data', sa.JSON(), nullable=False, comment='User-provided form values'),
    sa.Column('generated_text', sa.Text(), nullable=False, comment='The generated document content'),
    sa.Column('file_path', sa.String(length=500), nullable=True, comment='Path to generated PDF file'),
    sa.Column('is_downloaded', sa.Boolean(), nullable=False, comment='Whether user has downloaded this document'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], name=op.f('fk_generated_documents_template_id_templates'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_generated_documents_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generated_documents'))
    )
    op.create_index(op.f('ix_generated_documents_id'), 'generated_documents', ['id'], unique=False)
    op.create_index(op.f('ix_generated_documents_template_id'), 'generated_documents', ['template_id'], unique=False)
    op.create_index(op.f('ix_generated_documents_user_id'), 'generated_documents', ['user_id'], unique=False)
    op.create_table('knowledge_base',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False, comment="Document title (e.g., 'Indian Contract Act, 1872')"),
    sa.Column('description', sa.Text(), nullable=True, comment='Description of the document content'),
    sa.Column('source', sa.String(length=255), nullable=True, comment="Source of the document (e.g., 'Government of India')"),
    sa.Column('source_url', sa.String(length=500), nullable=True, comment='URL to original source (if available)'),
    sa.Column('category', sa.String(length=100), nullable=False, comment='Category: acts, rules, judgments, guides'),
    sa.Column('tags', sa.JSON(), nullable=True, comment="Tags for filtering: ['contract', 'commercial', 'civil']"),
    sa.Column('file_path', sa.String(length=500), nullable=True, comment='Path to original uploaded file'),
    sa.Column('file_type', sa.String(length=50), nullable=True, comment='File type: pdf, txt'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Status: pending, processing, ready, failed'),
    sa.Column('chunk_count', sa.Integer(), nullable=False, comment='Number of chunks created'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether this document is used in searches'),
    sa.Column('uploaded_by', sa.String(length=36), nullable=True, comment='Admin who uploaded this document'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_knowledge_base_uploaded_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_base'))
    )
    op.create_index(op.f('ix_knowledge_base_category'), 'knowledge_base', ['category'], unique=False)
    op.create_index(op.f('ix_knowledge_base_id'), 'knowledge_base', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_base_status'), 'knowledge_base', ['status'], unique=False)
    op.create_index(op.f('ix_knowledge_base_title'), 'knowledge_base', ['title'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='Owner of this chat session'),
    sa.Column('document_id', sa.String(length=36), nullable=True, comment='Document being discussed (if any)'),
    sa.Column('title', sa.String(length=255), nullable=True, comment='Session title (auto-generated from first message)'),
    sa.Column('session_type', sa.String(length=20), nullable=False, comment='Type: general or document'),
    sa.Column('message_count', sa.Integer(), nullable=False, comment='Number of messages in session'),
    sa.Column('total_tokens', sa.Integer(), nullable=False, comment='Total tokens used in this session'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Last activity timestamp'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_chat_sessions_document_id_documents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_chat_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_sessions'))
    )
    op.create_index(op.f('ix_chat_sessions_document_id'), 'chat_sessions', ['document_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_id'), 'chat_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_session_type'), 'chat_sessions', ['session_type'], unique=False)
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False, comment='Position of chunk in document (0-indexed)'),
    sa.Column('content', sa.Text(), nullable=False, comment='The actual text content of this chunk'),
    sa.Column('start_char', sa.Integer(), nullable=True, comment='Starting character position in original document'),
    sa.Column('end_char', sa.Integer(), nullable=True, comment='Ending character position in original document'),
    sa.Column('start_page', sa.Integer(), nullable=True, comment='Starting page number (1-indexed, for PDFs)'),
    sa.Column('end_page', sa.Integer(), nullable=True, comment='Ending page number (for chunks spanning pages)'),
    sa.Column('chroma_id', sa.String(length=100), nullable=True, comment='ID in ChromaDB vector store'),
    sa.Column('metadata', sa.JSON(), nullable=True, comment='Additional metadata (headers, formatting, etc.)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_chunks_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_chunks'))
    )
    op.create_index(op.f('ix_document_chunks_chroma_id'), 'document_chunks', ['chroma_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_id'), 'document_chunks', ['id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False, comment='Role: user, assistant, or system'),
    sa.Column('content', sa.Text(), nullable=False, comment='The message text content'),
    sa.Column('sources', sa.JSON(), nullable=True, comment='Sources/chunks used for this response'),
    sa.Column('tokens_used', sa.Integer(), nullable=True, comment='Tokens used for this message'),
    sa.Column('model_used', sa.String(length=100), nullable=True, comment='LLM model used for this response'),
    sa.Column('generation_time_ms', sa.Integer(), nullable=True, comment='Time taken to generate response (milliseconds)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], name=op.f('fk_chat_messages_session_id_chat_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages'))
    )
    op.create_index(op.f('ix_chat_messages_created_at'), 'chat_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_created_at'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_document_chunks_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_chroma_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_session_type'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_document_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_knowledge_base_title'), table_name='knowledge_base')
    op.drop_index(op.f('ix_knowledge_base_status'), table_name='knowledge_base')
    op.drop_index(op.f('ix_knowledge_base_id'), table_name='knowledge_base')
    op.drop_index(op.f('ix_knowledge_base_category'), table_name='knowledge_base')
    op.drop_table('knowledge_base')
    op.drop_index(op.f('ix_generated_documents_user_id'), table_name='generated_documents')
    op.drop_index(op.f('ix_generated_documents_template_id'), table_name='generated_documents')
    op.drop_index(op.f('ix_generated_documents_id'), table_name='generated_documents')
    op.drop_table('generated_documents')
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_templates_slug'), table_name='templates')
    op.drop_index(op.f('ix_templates_name'), table_name='templates')
    op.drop_index(op.f('ix_templates_id'), table_name='templates')
    op.drop_index(op.f('ix_templates_category'), table_name='templates')
    op.drop_table('templates')
    # ### end Alembic commands ###
